# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rengine}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["cloudwow"]
  s.date = %q{2011-04-26}
  s.description = %q{longer description of your gem}
  s.email = %q{david@cloudwow.com}
  s.executables = ["rengine_work", "rengine_work_control"]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/rengine.rb",
     "lib/rengine/acts_as_account_controller.rb",
     "lib/rengine/acts_as_log_writer.rb",
     "lib/rengine/acts_as_rengine_controller.rb",
     "lib/rengine/acts_as_weblab_controller.rb",
     "lib/rengine/blurb.rb",
     "lib/rengine/blurb_map.rb",
     "lib/rengine/blurb_wording.rb",
     "lib/rengine/error.rb",
     "lib/rengine/extensions/string.rb",
     "lib/rengine/facebook_oauth.rb",
     "lib/rengine/google_oauth.rb",
     "lib/rengine/http_accept_language.rb",
     "lib/rengine/imager.rb",
     "lib/rengine/language.rb",
     "lib/rengine/memory_blurb_map.rb",
     "lib/rengine/offline_worker.rb",
     "lib/rengine/page_cache_item.rb",
     "lib/rengine/render_base.rb",
     "lib/rengine/renderer.rb",
     "lib/rengine/static_file_manager.rb",
     "lib/rengine/translation_tool.rb",
     "lib/rengine/uri_util.rb",
     "lib/rengine/user.rb",
     "lib/rengine/views/single_translation_tool.html.erb",
     "lib/rengine/views/translation_tool.html.erb",
     "lib/rengine/weblab.rb",
     "lib/rengine/weblab_base.rb",
     "lib/rengine/work_request.rb",
     "lib/rengine/work_result.rb",
     "lib/rengine/yahoo_oauth.rb"
  ]
  s.homepage = %q{http://github.com/cloudwow/rengine}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{one-line summary of your gem}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<oauth>, [">= 0"])
      s.add_runtime_dependency(%q<portablecontacts>, [">= 0"])
      s.add_runtime_dependency(%q<nanikore>, [">= 0"])
      s.add_runtime_dependency(%q<xml-simple>, [">= 0"])
      s.add_runtime_dependency(%q<erubis>, [">= 0"])
      s.add_runtime_dependency(%q<not_relational>, [">= 0"])
      s.add_runtime_dependency(%q<image_science>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<oauth>, [">= 0"])
      s.add_dependency(%q<portablecontacts>, [">= 0"])
      s.add_dependency(%q<nanikore>, [">= 0"])
      s.add_dependency(%q<xml-simple>, [">= 0"])
      s.add_dependency(%q<erubis>, [">= 0"])
      s.add_dependency(%q<not_relational>, [">= 0"])
      s.add_dependency(%q<image_science>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<oauth>, [">= 0"])
    s.add_dependency(%q<portablecontacts>, [">= 0"])
    s.add_dependency(%q<nanikore>, [">= 0"])
    s.add_dependency(%q<xml-simple>, [">= 0"])
    s.add_dependency(%q<erubis>, [">= 0"])
    s.add_dependency(%q<not_relational>, [">= 0"])
    s.add_dependency(%q<image_science>, [">= 0"])
  end
end

