test_not_relational:
  aws_key_id: abc
  aws_secret_key: q13123
  base_domain_name: rengine_test
  blob_bucket: rengine_test
  sqs_work_queue: rengine_test
  use_seperate_domain_per_model: false
  repository_class: NotRelational::MemoryRepository
  log_level: WARN
  cipher_password: devadfwas

test_aws_not_relational:
  aws_key_id: 0QZR9BFFZXJWMDGXSD02
  aws_secret_key: nHeMPHjiWuXR3D/pzk1H+SvlqCcIMKFLwa2KhvmR
  base_domain_name: rengine_test
  blob_bucket: rengine_test
  sqs_work_queue: rengine_test
  use_seperate_domain_per_model: false
  repository_class: NotRelational::MemoryRepository
  log_level: DEBUG
  cipher_password: dev12ad12
